# REST Client allows you to send HTTP request and view the response in Visual Studio Code directly.
# see: https://github.com/Huachao/vscode-restclient/


@host = http://127.0.0.1:5001

###
GET {{host}}/api/user?id:le=3&name:nc=aa&_join=user_address

###
GET {{host}}/api/user/1

###
POST {{host}}/api/user
Content-Type: application/json

{
    "name": "name123",
    "key2": null,
    "key3": "{\"aa\": 123}"
}

###
PUT {{host}}/api/user/1
Content-Type: application/json

{
    "name":"aaname1",
    "ctime1": "2021 10 10 10:10",
    "ctime2": "2021/11/11",
    "ctime3": "12:12:12",
    "key_float": 12.123,
    "age": 123,
    "enabled": null
}
###
GET {{host}}/api/user_address

###
POST {{host}}/api/user_address
Content-Type: application/json

{
    "user_id": 22,
    "address":"address444"
}

###
DELETE {{host}}/api/user_address/1